### ISSUE TITLE
[BUG] JWT-Editor not loading

### ISSUE THREAD

**Issue by sebastianosrt** [DolphFlynn/jwt-editor#32]
During a security assestment, where I was using this Burp extension, my PC crashed and after that the extension won't load anymore (both in Burp Pro and Community edition).

**Things i tried**
- reloading Burp, as well as my PC
- removing and reinstalling the extension
- updating Burp to the latest version
- installing the extension from the compiled jar

**Error message**
```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at com.blackberry.jwteditor.view.config.IntruderConfigModel.signingAlgorithms(IntruderConfigModel.java:102)
	at com.blackberry.jwteditor.view.config.IntruderConfigModel.<init>(IntruderConfigModel.java:38)
	at com.blackberry.jwteditor.view.config.ConfigView.createUIComponents(ConfigView.java:48)
	at com.blackberry.jwteditor.view.config.ConfigView.$$$setupUI$$$(ConfigView.java)
	at com.blackberry.jwteditor.view.config.ConfigView.<init>(ConfigView.java:44)
	at com.blackberry.jwteditor.view.SuiteView.createUIComponents(SuiteView.java:97)
	at com.blackberry.jwteditor.view.SuiteView.$$$setupUI$$$(SuiteView.java)
	at com.blackberry.jwteditor.view.SuiteView.<init>(SuiteView.java:68)
	at burp.JWTEditorExtension.initialize(JWTEditorExtension.java:57)
	at burp.Zpda.Zx(Unknown Source)
	at burp.Zpvs.ZO(Unknown Source)
	at burp.Zpvq.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by DolphFlynn** [comment]
Hi @sebastianosrt,

It sounds like the config has got into a weird state. I'd suggest deleting this (or at least removing the Intruder specific part) and seeing if that fixes the issue. The data is within the Java preferences store so its location is going to be platform specific, but once you find it then it's a list of name value pairs. The interesting one is keyed on 'string_com.blackberry.jwteditor.settings'. The value is encoded JSON so if you can post that then I can see what the underlying issue is.

**Comment by sebastianosrt** [comment]
Hi,
Thank you I solved It removing completely the prefs, that I found under this path:
```rm .java/.userPrefs/burp/extensions/_\!\&8\!\]g\"\|\!\&@\!\)\!\"\&\!\'@\!a@\"0\!\'8\!cg==/prefs.xml ```

Here you can find its contents:
```
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="string_com.blackberry.jwteditor.keystore" value="[{&quot;kty&quot;:&quot;RSA&quot;,&quot;x5t#S256&quot;:&quot;AbulYyEMgASQ_N8S_FiWgoMNeT0q4Pu5rMKFc1m9YDs&quot;,&quot;e&quot;:&quot;AQAB&quot;,&quot;use&quot;:&quot;sig&quot;,&quot;x5t&quot;:&quot;9f_KFyu6DwwzxKC5nz76dTbCRgE&quot;,&quot;kid&quot;:&quot;njJgWzxMQSarMfvxK5bJ6ejo1AH-DmvXNCdsbfnv-cY&quot;,&quot;x5c&quot;:[&quot;MIIClTCCAX0CBgFydTAgQjANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANTQlAwHhcNMjAwNjAyMTMxODA3WhcNMzAwNjAyMTMxOTQ3WjAOMQwwCgYDVQQDDANTQlAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOTIcesYvvrvYqf23U+SCRJ6XHjUvvx3RVNTsgpxqEflJvHo1Z/PBiNbh7ckDApo8gt7SvSnsDG+zYrH8bcPWMcPnvf42YMjCY3SmtzjHWpw6z8nEbNMk3zqE4HjSdwYiS1+ndRt+7u0lFfoJEC+M3tWOukxHgaI+NSQfoHE5Ncbm0cqnuQrFu0oQbh2gXlFefB9DYbgS6FGE1mb6S7z358BZ+3gqoCf3snbYPyYa38QADD0va9aTw1zPmAjOvXubcEMd57uUwtXfkMgw3NNjr5R8gZYY9/Ueim8zB4oXCQTs03M9g8LlwVR827x0pB2W/r1SMH0rtkkYIOO8yy4gnAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAJfuyot3Z63EdzNwVusXli5xe9eH7IumNXEW6WEu+Q7aoJ+22FiIyika2VaiDp+fHJ2XFG5C+L+pKPRaW89C41N2nyy9CywRnE4jYbjbSUAC6cIFNQ1nSmNTh1hass7mbBJiSvH6qSbnXvmAfelnbl5uNbviX0omrAXVm2l+bAZ+uT4Sxy8quqRtgyfP41cYOq5WVvmQ8KfkiG6Z9Dh3y2H3P25nAixGWN8SdL90OI7flOXp8d0Qo6trTacGmSV5+rR2K6vzBSBWZToh36zV9l47y4oxk/rkOt1uBeEzLV08yS3T8KpndiX/i3tKd86SEo4yXZyEyHCzXA3BIZgkYt4=&quot;],&quot;alg&quot;:&quot;RS256&quot;,&quot;n&quot;:&quot;zkyHHrGL7672Kn9t1PkgkSelx41L78d0VTU7IKcahH5Sbx6NWfzwYjW4e3JAwKaPILe0r0p7Axvs2Kx_G3D1jHD573-NmDIwmN0prc4x1qcOs_JxGzTJN86hOB40ncGIktfp3Ubfu7tJRX6CRAvjN7VjrpMR4GiPjUkH6BxOTXG5tHKp7kKxbtKEG4doF5RXnwfQ2G4EuhRhNZm-ku89-fAWft4KqAn97J22D8mGt_EAAw9L2vWk8Ncz5gIzr17m3BDHee7lMLV35DIMNzTY6-UfIGWGPf1HopvMweKFwkE7NNzPYPC5cFUfNu8dKQdlv69UjB9K7ZJGCDjvMsuIJw&quot;}]"/>
  <entry key="string_com.blackberry.jwteditor.settings" value="{&quot;scanner_insertion_point_provider_enabled&quot;:false,&quot;intruder_payload_processor_signing_algorithm&quot;:&quot;HS256&quot;,&quot;intruder_payload_processor_parameter_name&quot;:&quot;name&quot;,&quot;intruder_payload_processor_signing_key_id&quot;:&quot;27f68f1c-0b06-4612-8e98-75ac1738ebcf&quot;,&quot;proxy_history_highlight_color&quot;:&quot;GREEN&quot;,&quot;proxy_listener_enabled&quot;:true,&quot;scanner_insertion_point_provider_parameter_name&quot;:&quot;kid&quot;,&quot;intruder_payload_processor_resign&quot;:false,&quot;intruder_payload_processor_fuzz_location&quot;:&quot;PAYLOAD&quot;}"/>
</map>
```
