### ISSUE TITLE
[BUG]After using the plugin, the signature section was not updated.

### ISSUE THREAD

**Issue by oxsee** [DolphFlynn/jwt-editor#40]
I encountered some issues while handling the burpsuite lab: "JWT authentication bypass via kid header path traversal" using the JWT Editor v2.2.1 plugin. Following the lab's steps:

1、Go to the JWT Editor Keys tab in Burp's main tab bar.

2、Click New Symmetric Key.

4、In the dialog, click Generate to generate a new key in JWK format. Note that you don't need to select a key size as this will automatically be updated later.

5、Replace the generated value for the k property with a Base64-encoded null byte (AA==). Note that this is just a workaround because the JWT Editor extension won't allow you to sign tokens using an empty string.

6、Click OK to save the key.

7、Go back to the GET /admin request in Burp Repeater and switch to the extension-generated JSON Web Token message editor tab.
返回Burp Repeater中的 GET /admin 请求，并切换到扩展生成的JSON Web Token消息编辑器选项卡。

8、In the header of the JWT, change the value of the kid parameter to a path traversal sequence pointing to the /dev/null file:../../../../../../../dev/null

9、In the JWT payload, change the value of the sub claim to administrator.

10、At the bottom of the tab, click Sign, then select the symmetric key that you generated in the previous section.

At step 10, I encountered a problem. I selected the "Don't modify header" option and clicked OK. However, I found that my key section was not updated, which caused the lab to fail. Do you know how to resolve this issue?

JWT Without using sign > Don't modify：
![image](https://github.com/user-attachments/assets/1497c2b5-a16c-42a5-8dba-396a8fdab3e3)

JWT Using sign > Don't modify：
![image](https://github.com/user-attachments/assets/d0bbecd1-5ad2-4a59-bf3f-941521015549)
![image](https://github.com/user-attachments/assets/583538a8-dabc-4aa8-bb9c-7a0304073306)

**Comment by oxsee** [comment]
My Burp Suite version is v2024.6

**Comment by DolphFlynn** [comment]
Thanks for the report. Are you seeing any errors either logged to the Errors panel within Extension or to the console if running from the shell?

As an aside, you don't need the AA== workaround as you can use Attack -> Sign with empty key.

**Comment by oxsee** [comment]
> Thanks for the report. Are you seeing any errors either logged to the Errors panel within Extension or to the console if running from the shell?
> 
> As an aside, you don't need the AA== workaround as you can use Attack -> Sign with empty key.



my use Attack -> Sign with empty key. The signature also did not change, and when I sent the request, I still received a 401 response.

There was indeed an error within the extension. The error message is as follows:
	at com.nimbusds.jose.crypto.impl.HMAC.getInitMac(HMAC.java:52)
	at com.nimbusds.jose.crypto.impl.HMAC.compute(HMAC.java:118)
	at com.nimbusds.jose.crypto.impl.HMAC.compute(HMAC.java:94)
	at com.nimbusds.jose.crypto.MACSigner.sign(MACSigner.java:193)
	at com.blackberry.jwteditor.model.jose.JWSSigner.sign(JWSSigner.java:63)
	at com.blackberry.jwteditor.model.jose.JWSFactory.sign(JWSFactory.java:86)
	at com.blackberry.jwteditor.operations.Attacks.signWithEmptyKey(Attacks.java:119)
	at com.blackberry.jwteditor.view.dialog.operations.EmptyKeySigningDialog.onOK(EmptyKeySigningDialog.java:73)
	at com.blackberry.jwteditor.view.dialog.operations.EmptyKeySigningDialog.lambda$new$0(EmptyKeySigningDialog.java:51)
	at com.blackberry.jwteditor.view.utils.ErrorLoggingActionListener.actionPerformed(ErrorLoggingActionListener.java:40)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at burp.Zpvb.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
	at com.blackberry.jwteditor.view.dialog.AbstractDialog.display(AbstractDialog.java:47)
	at com.blackberry.jwteditor.presenter.EditorPresenter.onAttackSignEmptyKeyClicked(EditorPresenter.java:300)
	at com.blackberry.jwteditor.view.editor.EditorView.lambda$createUIComponents$15(EditorView.java:524)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at burp.Zpvb.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.jar.JarException: The JCE Provider file:/D:/Test_Tools/Hk_Tools/1-Flow_Tools/Burp/burpsuite_pro_v2024.5.1/burpsuite_pro_v2024.6.2.jar is not signed.
	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:440)
	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:319)
	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:263)
	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:196)
	at java.base/javax.crypto.JceSecurity$2.apply(JceSecurity.java:222)
	at java.base/javax.crypto.JceSecurity$2.apply(JceSecurity.java:211)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:211)
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:146)
	... 95 more

**Comment by DolphFlynn** [comment]
@oxsee Thanks for the stacktrace. I can see the problem.


The method at the top of the stack trace is triggering the loading of the Bouncy Castle cryptography library, which is your JRE is refusing to load:

**Caused by: java.util.jar.JarException: The JCE Provider file:/D:/Test_Tools/Hk_Tools/1-Flow_Tools/Burp/burpsuite_pro_v2024.5.1/burpsuite_pro_v2024.6.2.jar is not signed.**

JWT Editor uses the Bouncy Castle bundled with Burp so this suggests that there's something wrong with your JAR or something special about the version of Java you're using (e.g. there's a custom security policy).

Can you download an installer based version of Burp which should include it's own version of Java? How are you launching Burp and which vendor/version of Java are you using?

**Comment by oxsee** [comment]
I created a BAT script to open my Burp Suite. The content is as follows:

Dim ws, javaPath
Set ws = CreateObject("WScript.Shell")


javaPath = "D:\Develop\Java\jdk-21\bin\java.exe"

ws.Run """" & javaPath & """ --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -javaagent:BurpLoaderKeygen.jar -javaagent:ja-netfilter.jar -Dsun.java2d.d3d=false -noverify -Dsun.java2d.uiScale=1 -jar burpsuite_pro_v2024.6.2.jar", 0

**Comment by DolphFlynn** [comment]
Oh that's interesting. So you're running the license crack and an instrumentation library one of which I suspect is the problem. 

If you run without the Java agent then you should have more success. Out of interest, why are you using the ja-netfilter library?

In terms of JWT Editor, I think the exception handling needs to be improved so I'll aim to do this in the near future.

**Comment by oxsee** [comment]
It seems that ja-netfilter.jar is a tool for cracking Burp Suite. I am a student and don’t have much money. I have to travel about seven or eight kilometers each day to use a shared computer for my studies. Therefore, I found this cracked program online to use for my learning. Thank you for your help.

**Comment by oxsee** [comment]
I have found that not only the empty key, but also any key created using "New Symmetric Key," results in the issue described above

**Comment by DolphFlynn** [comment]
That makes sense as the cryptographic library that does the signing is being prevented from loading (presumably as a consequence of the license crack).

I suggest that you use the [free version of Burp](https://portswigger.net/burp/releases/professional-community-2024-5-5?requestededition=community) which won't have this problem. You should be able to go a long way using this for your education. 

Good luck with your studies!
