### ISSUE TITLE
[BUG] JWT Signing Fails in Burp Suite .jar Versions

### ISSUE THREAD

**Issue by MasoudAbdaal** [DolphFlynn/jwt-editor#78]
**Expected Behavior**
The modified JWT token should be correctly signed using the specified algorithm and key, producing a valid token using the `.jar` version of Burp Suite.

**Current Behavior**
When attempting to re-sign a modified JWT token using the .jar version of the Burp Suite, the signing process either does not complete or produces an invalid token. As a result, the modified token fails validation or cannot be used in subsequent requests.

**Steps To Reproduce**
1. Run Burp Suite (`.jar` version) and load/install the JWT Editor extension.
2. Intercept a request containing a JWT token.
3. Modify the payload or header of the token using the JWT Editor.
4. Attempt to re-sign the token using a valid private key or algorithm.
5. Observe that the token is not signed correctly or fails validation.

**Additional Information**
This issue might relate to the previously reported [Issue #69](https://github.com/DolphFlynn/jwt-editor/issues/69), but it appears unresolved for the `.jar` version. It significantly impacts the tool's usability for testing modified JWTs in real-world scenarios.

**Environment**
JWT Editor Version: latest release
Burp Suite Version: v2024.11.2
Java Version: java 21.0.1 2023-10-17 LTS, Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29), Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
Operating System: Windows 10 Version	10.0.19045 Build 19045

**Comment by DolphFlynn** [comment]
Thanks for the report. Are you seeing any errors either logged to the Errors panel within Extension or to the console if running from the shell?

**Comment by MasoudAbdaal** [comment]
When I modify the token and try to "**Sign**", I get no error on the console and no changes on the token signature; But when I try to "**Verify**" I get this error and a red border comes into "Serialized JWT" section"

Console Error:
```java
java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:150)
        at java.base/javax.crypto.Mac.getInstance(Mac.java:272)
        at com.nimbusds.jose.crypto.impl.HMAC.getInitMac(HMAC.java:52)
        at com.nimbusds.jose.crypto.impl.HMAC.compute(HMAC.java:118)
        at com.nimbusds.jose.crypto.impl.HMAC.compute(HMAC.java:94)
        at com.nimbusds.jose.crypto.MACVerifier.verify(MACVerifier.java:199)
        at com.blackberry.jwteditor.model.jose.JWS.verify(JWS.java:125)
        at com.blackberry.jwteditor.model.keys.KeyRing.findVerifyingKey(KeyRing.java:44)
        at com.blackberry.jwteditor.presenter.EditorPresenter.onVerifyClicked(EditorPresenter.java:326)
        at com.blackberry.jwteditor.view.editor.EditorView.lambda$new$10(EditorView.java:170)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/java.awt.Component.processEvent(Component.java:6386)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at burp.Zimh.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Red boarders comes to "Serialized JWT" Section After Modify Token
![Verify Modified JWT Token](https://github.com/user-attachments/assets/32e83b72-40d6-41cf-a872-ab39e7030107)


My command used to run the BurpSuite.jar file:
```powershell
java -jar -Xmx4g D:\Apps\burpsuite_community_v2024.11.2.jar --diagnostics  --config-file=D:\Apps\projectSettings.json --user-config-file=D:\Apps\userSettings.json
````

**Comment by DolphFlynn** [comment]
Thanks for the information. The signing operation is failing as the underlying cryptography provider is failing to load. 

I've just tried to replicate this with Community v2024.11.2 and everything seems fine.

What other extensions do you have loaded?

**Comment by MasoudAbdaal** [comment]
I have no extension loading by default when BurpSuite starts and enable JWT Editor manually.

My BurpSuite Extensions:
| Loaded | Type   | Name                                       | System Impact |
| ------ | ------ | ------------------------------------------ | ------------- |
| false  | Java   | Logger++                                   | HIGH          |
| false  | Java   | Param Miner                                | LOW           |
| false  | Java   | Turbo Intruder                             | MEDIUM        |
| false  | Java   | CSP Auditor                                | LOW           |
| false  | Java   | HTTP Request Smuggler                      | LOW           |
| false  | Python | GAP (Get All Parameters, Links, and Words) | LOW           |
| false  | Python | Autorize                                   | LOW           |
| false  | Java   | IIS Tilde Enumeration Scanner              | LOW           |
| false  | Python | SSL Scanner                                | LOW           |
| false  | Java   | Hackvertor                                 | LOW           |
| false  | Java   | JWT Editor                                 | LOW           |

**Comment by DolphFlynn** [comment]
That's really strange. JWT Editor uses the Bouncy Castle that is internal to Burp, so it's weird that there's an issue loading this. I would assume that whatever Burp needs the Bouncy Castle for itself will also fail.

I've only ever seen that above stack trace when the Burp license crack is in use, so I have no idea why it would occur with Community. At this point, you  probably need to contact PortSwigger's support for advice as this is essentially a Burp problem not a JWT Editor problem. 

Long term, the Bouncy Castle is only really needed for JWS with ES256K so I could look to limit it's use. This is kind of fixing the symptom not the underlying problem though.

**Comment by DolphFlynn** [comment]
I tested with openjdk version 21.0.2 and the Community JAR v2024.12.2. Which version / vendor of Java are you using?

**Comment by DolphFlynn** [comment]
No success reproducing the issue with all your extensions installed.

**Comment by MasoudAbdaal** [comment]
> I tested with openjdk version 21.0.2 and the Community JAR v2024.12.2. Which version / vendor of Java are you using?

java -version
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

**Comment by DolphFlynn** [comment]
Can you paste the output of the command line when you start with --diagnostics?

**Comment by MasoudAbdaal** [comment]
```powershell
java -jar -Xmx4g D:\Apps\burpsuite_community_v2024.11.2.jar --diagnostics  --config-file=D:\Apps\projectSettings.json --user-config-file=D:\Apps\userSettings.json
---------------------------------------------------------------------------------------------------------
SYSTEM PROPERTIES
---------------------------------------------------------------------------------------------------------
awt.dnd.drag.threshold           15
com.sun.net.ssl.requireCloseNotify false
file.encoding                    UTF-8
file.separator                   \
flatlaf.uiScale.enabled          false
java.class.path                  D:\Apps\burpsuite_community_v2024.11.2.jar
java.class.version               65.0
java.home                        D:\Apps\jdk-21.0.1
java.io.tmpdir                   C:\Users\Dynamic\AppData\Local\Temp\
java.library.path                D:\Apps\jdk-21.0.1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;D:\Apps\Python
java.runtime.name                Java(TM) SE Runtime Environment
java.runtime.version             21.0.1+12-LTS-29
java.specification.name          Java Platform API Specification
java.specification.vendor        Oracle Corporation
java.specification.version       21
java.vendor                      Oracle Corporation
java.vendor.url                  https://java.oracle.com/
java.vendor.url.bug              https://bugreport.java.com/bugreport/
java.version                     21.0.1
java.version.date                2023-10-17
java.vm.compressedOopsMode       Zero based
java.vm.info                     mixed mode, sharing
java.vm.name                     Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name       Java Virtual Machine Specification
java.vm.specification.vendor     Oracle Corporation
java.vm.specification.version    21
java.vm.vendor                   Oracle Corporation
java.vm.version                  21.0.1+12-LTS-29
jdk.debug                        release
jdk.tls.allowUnsafeServerCertChange true
jdk.tls.maxCertificateChainLength 1337
native.encoding                  Cp1252
org.bouncycastle.jsse.client.dh.minimumPrimeBits 1024
org.bouncycastle.jsse.client.dh.unrestrictedGroups true
os.arch                          amd64
os.name                          Windows 10
os.version                       10.0
path.separator                   ;
stderr.encoding                  cp437
stdout.encoding                  cp437
sun.arch.data.model              64
sun.awt.enableExtraMouseButtons  true
sun.boot.library.path            D:\Apps\jdk-21.0.1\bin
sun.cpu.endian                   little
sun.cpu.isalist                  amd64
sun.io.unicode.encoding          UnicodeLittle
sun.java.command                 D:\Apps\burpsuite_community_v2024.11.2.jar --diagnostics --config-file=D:\Apps\projectSettings.json --user-config-file=D:\Apps\userSettings.json
sun.java.launcher                SUN_STANDARD
sun.java2d.dpiaware              true
sun.java2d.uiScale               1.25
sun.jnu.encoding                 Cp1252
sun.management.compiler          HotSpot 64-Bit Tiered Compilers
sun.os.patch.level
user.country                     US
user.dir                         C:\Users\Dynamic\Desktop
user.home                        C:\Users\Dynamic
user.language                    en
user.name                        Dynamic
user.script
user.timezone                    Asia/Tehran
user.variant

---------------------------------------------------------------------------------------------------------
SYSTEM RESOURCES
---------------------------------------------------------------------------------------------------------
Number of processors             8
Total JVM memory                 114 MiB
Max JVM memory                   4 GiB
Free JVM memory                  69.41 MiB

Total physical memory            11.9 GiB
Free physical memory             6.49 GiB
Total swap                       13.71 GiB
Free swap                        7.46 GiB

---------------------------------------------------------------------------------------------------------
BURP PROPERTIES
---------------------------------------------------------------------------------------------------------
Burp Version                     2024.11.2
Build Number                     34792
Product Name                     Burp Suite Community Edition
Burp Browser                     [version=131.0.6778.140, installationPath=C:\Users\Dynamic\AppData\Roaming\BurpSuite\burpbrowser\131.0.6778.140]
Code source                      D:\Apps\burpsuite_community_v2024.11.2.jar
Debug ID                         ndmbc98pajw5nkkfpttv:qtp3
JAR type                         Standalone
currenttimemillis                1735621411855
nanotime                         6103782522400
```

**Comment by DolphFlynn** [comment]
I think we're reached the limits of what I can do here without being able to reproduce the issue myself.

You'll need to contact PortSwigger. A skeleton BApp that simply loads the Bouncy Castle is presumably going to fail so I suggest this is a good place to start.

I'll leave this issue open for now so that you can post back your findings. Good luck!

**Comment by DolphFlynn** [comment]
Final thought! Do you have custom security policy in place? Can you try running with default OpenJDK 21.0.2?

**Comment by MasoudAbdaal** [comment]
Happy New Year, DolphFlynn! I hope this year brings you all the success and happiness you desire. 

I’m so sorry for taking the time to get back to you. I followed your suggestion and updated my Java to `OpenJDK 23.0.1 2024-10-15`, and I’m happy to report that it solved my problem! 

- [x] Signature modified successfully 
- [x] The verify token is working great now and no longer throws exceptions 

Thanks a bunch for your help! I'm grateful!

**Comment by DolphFlynn** [comment]
@MasoudAbdaal That's great news that the alternative JVM resolved your issue. Have a fantastic 2025 as well.
